In [1]:
import pandas as pd
from pathlib import Path
from datetime import datetime as dt

from sklearn_crfsuite import CRF
from sklearn_crfsuite.metrics import flat_classification_report
from sklearn_crfsuite.metrics import sequence_accuracy_score
from sklearn.model_selection import cross_val_predict

In [2]:
path="input22.xlsx"

In [3]:
xlsx = pd.ExcelFile(path)
df=pd.read_excel(xlsx, header=None)
df

            0      1
0           ب      O
1          أ)      O
2        أعلن      O
3       اتحاد  B-ORG
4       صناعة  I-ORG
5    السيارات  I-ORG
6          في      O
7     ألمانيا  B-LOC
8         امس      O
9       الاول      O
10         أن      O
11      شركات      O
12      صناعة      O
13   السيارات      O
14         في      O
15    ألمانيا  B-LOC
16      تواجه      O
17       عاما      O
18       صعبا      O
19         في      O
20         ظل      O
21       ركود      O
22      السوق      O
23   الداخلية      O
24  والصادرات      O
25        وهي      O
26       تسعي      O
27        لان      O
28       يبلغ      O
29    الانتاج      O
30      حوالي      O
31       خمسة      O
32     ملايين      O
33      سيارة      O
34         في      O
35        عام      O

In [4]:
# df = df.drop(2, 1)
df = df.rename(columns={0: 'text', 1: 'label'})
df

         text  label
0           ب      O
1          أ)      O
2        أعلن      O
3       اتحاد  B-ORG
4       صناعة  I-ORG
5    السيارات  I-ORG
6          في      O
7     ألمانيا  B-LOC
8         امس      O
9       الاول      O
10         أن      O
11      شركات      O
12      صناعة      O
13   السيارات      O
14         في      O
15    ألمانيا  B-LOC
16      تواجه      O
17       عاما      O
18       صعبا      O
19         في      O
20         ظل      O
21       ركود      O
22      السوق      O
23   الداخلية      O
24  والصادرات      O
25        وهي      O
26       تسعي      O
27        لان      O
28       يبلغ      O
29    الانتاج      O
30      حوالي      O
31       خمسة      O
32     ملايين      O
33      سيارة      O
34         في      O
35        عام      O

In [5]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df, test_size = 0.2)
X_te = []
Y_te = []

X_tr = []
Y_tr = []

In [6]:
X_tr=train['text'].astype(str)
Y_tr=train['label'].astype(str)

X_te=test['text'].astype(str)
Y_te=test['label'].astype(str)

In [7]:
X_te.shape

(8,)

In [8]:
Y_te.shape

(8,)

In [9]:
X_tr.shape

(28,)

In [10]:
Y_tr.shape

(28,)

In [11]:
crf = CRF(algorithm='lbfgs', c1=0.1, c2=0.1, max_iterations=100000, all_possible_transitions=False)

In [12]:
crf.fit(X_tr, Y_tr)

ValueError: The numbers of items and labels differ: |x| = 3, |y| = 1